ARG RUBY_VER=3.1.7
ARG DEBIAN_REL=trixie
FROM docker.io/library/ruby:${RUBY_VER}-slim-${DEBIAN_REL}

RUN --mount=type=bind,target=/buildcontext \
    set -eux; \
    apt-get update; \
    /buildcontext/install_useful_packages.sh; \
    rm -rf /var/lib/apt/lists/*;

COPY util/20-set-docker-prompt.sh /etc/profile.d/
