---
name: push
on:
  push:
    branches: [main]
permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  build-image:
    runs-on: ubuntu-24.04-16-core
    strategy:
      fail-fast: false
      matrix:
        ruby-ver: ["3.3.5"]
        debian-rel: ["trixie"]
        platforms: ["linux/amd64,linux/arm64"]
        include:
        - ruby-ver: "2.6.8"
          debian-rel: "bullseye"
          platforms: linux/amd64
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup
      id: setup
      run: |
        local ruby_ver='${{ matrix.ruby-ver }}'
        local debian_rel='${{ matrix.debian-rel }}'
        local tag="${ruby_ver}-${debian_rel}"
        local dockerfile="${tag}/Dockerfile"
        echo "Dockerfile=$dockerfile" >> "$GITHUB_OUTPUT"
        local repo='ghcr.io/broadstripes/ruby'
        echo "tags=${repo}:${tag}" >> "$GITHUB_OUTPUT"
        echo "cache=${repo}:${tag}-buildcache" >> "$GITHUB_OUTPUT"
    - name: Build & Push
      uses: docker/build-push-action@v6
      with:
        push: true
        file: ${{ steps.setup.outputs.Dockerfile }}
        tags: ${{ steps.setup.outputs.tags }}
        platforms: ${{ matrix.platforms }}
        cache-from: type=registry,ref=${{ steps.setup.outputs.cache }},mode=max
        cache-to: type=registry,ref=${{ steps.setup.outputs.cache }},mode=max
