---
name: push
on:
  push:
    branches: [main]
permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        run: |
          set -eux
          echo 'matrix<<EOF' >> "$GITHUB_OUTPUT"
          cat <<JSON >>"$GITHUB_OUTPUT"
          {
            "ruby-ver": ["3.1.7","3.3.5"],
            "debian-rel": ["trixie"],
            "runners": ['["ubuntu-24.04","ubuntu-24.04-arm"]'],
            "include": [
              {
                "ruby-ver": "2.6.8",
                "debian-rel": "bullseye",
                "runners": '["ubuntu-24.04"]'
              }
            ]
          }
          JSON
          echo 'EOF' >> "$GITHUB_OUTPUT"
  multibuild:
    needs: [setup]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    uses: ./.github/workflows/build_multiplatform_image.yml
    secrets: inherit
    with:
      image: ghcr.io/broadstripes/ruby
      ruby-ver: ${{ matrix.ruby-ver }}
      debian-rel: ${{ matrix.debian-rel }}
      runners: ${{ matrix.runners }}
